"""Add landmark field to Extinguisher model

Revision ID: 21f62d1359c9
Revises: b6f85d422b7a
Create Date: 2025-04-12 18:49:46.169749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f62d1359c9'
down_revision = 'b6f85d422b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extinguishers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('landmark', sa.String(length=200), nullable=True))
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.create_unique_constraint('users_username_key', ['username'])

    with op.batch_alter_table('extinguishers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.drop_column('landmark')

    # ### end Alembic commands ###
