"""Add comments field to CheckInLog model

Revision ID: 52bac7e32a09
Revises: ec48cd5817fc
Create Date: 2025-04-12 19:05:38.767076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52bac7e32a09'
down_revision = 'ec48cd5817fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_in_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_in_logs', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
