"""Add image_filename to Extinguisher model

Revision ID: b6f85d422b7a
Revises: 
Create Date: 2025-04-12 13:25:50.290120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f85d422b7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extinguishers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extinguishers', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
