"""Add landmark field to Extinguisher model

Revision ID: ec48cd5817fc
Revises: 21f62d1359c9
Create Date: 2025-04-12 18:51:22.147582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec48cd5817fc'
down_revision = '21f62d1359c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extinguishers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extinguishers', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
